# Generated by Django 3.2.3 on 2021-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя или псевдоним')),
            ],
            options={
                'verbose_name': ('автор',),
                'verbose_name_plural': ('авторы',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': ('жанр',),
                'verbose_name_plural': ('жанры',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Издатель')),
            ],
            options={
                'verbose_name': ('издатель',),
                'verbose_name_plural': ('издатели',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Серия книг')),
            ],
            options={
                'verbose_name': ('серия',),
                'verbose_name_plural': ('серии',),
            },
        ),
    ]
